apiRules:
- include:
    uidRegex: ^DocFxForUnity
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: ^UnityEngine\.MonoBehaviour\..*$
    type: Member
- exclude:
    uidRegex: ^UnityEngine\.Behaviour\..*$
    type: Member
- exclude:
    uidRegex: ^UnityEngine\.Component\..*$
    type: Member
- exclude:
    uidRegex: ^UnityEngine\.Object\..*$
    type: Member
- exclude:
    uidRegex: ^CsvHelper\.Configuration\.ClassMap.*\..*$
    type: Member