name: .NET CI
on:
  push: { branches: [ main, dev ] }
  pull_request: { branches: [ main, dev ] }

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout ChargerAstronomyShared
        uses: actions/checkout@v4
        with:
          repository: CoperniSync/ChargerAstronomyShared   
          ref: dev                                        
          path: ChargerAstronomyShared                    

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
